django-calendar/cal/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'cal'
urlpatterns = [
    path('', views.CalendarView.as_view(), name='calendar'),
    path('new', views.new_event, name='new_event'),
	path('event<int:pk>', views.event, name='event'),
    path('edit_event/<int:pk>', views.edit, name='edit'),
    path('delete<int:pk>', views.delete, name='delete'), 
    path('delete_comment<int:pk>', views.delete_comment, name='delete_comment'), 
    path('comment_selection/<int:pk>', views.comment_selection, name='comment_selection'),
    path('delete_comment_selection/<int:pk>', views.delete_comment_selection, name='delete_comment_selection'), 
    path('edit_comment/<int:pk>', views.edit_comment, name='edit_comment'),
    path('upload/<int:pk>', views.image_upload_view,name='upload'),
    path('chat', views.chat, name='chat'), 
    path('weather/<int:pk>', views.weather, name='weather'),
    path('login_page', views.login_page, name='login_page'),
    path('register_page', views.register_page, name='register_page'), 
    path('logout_view', views.logout_view, name='logout_view'), 
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

django-calendar/chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

django-calendar/djangocalendar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cal.urls')),
    path("chat/", include("chat.urls")),
]

django-calendar/cal/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.db import models

class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    post_like = models.ManyToManyField(User,blank=True)
    def __str__(self):
      return self.title
    @property
    def get_html_url(self):
        url = reverse('cal:event', args=(self.id,))
        return f'<a href="{url}"> {self.title} </a>'
    

class CommentModel(models.Model):
  name = models.CharField(max_length=10)
  event = models.ForeignKey(Event,on_delete=models.SET_NULL,null=True,blank=True)  
  description = models.TextField(null=True,max_length=300)
  created = models.DateTimeField(auto_now_add=True,null=True)
  image = models.ImageField(upload_to='images',blank=True,null=True)
  video = models.FileField(upload_to='videos',null=True,blank=True)
  def __str__(self):
      return self.name 

django-calendar/cal/forms.py
from django.forms import ModelForm, DateInput
from cal.models import Event
from cal.models import CommentModel
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

class EventForm(ModelForm):
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
    }
    fields = '__all__'
    exclude=["post_like"]

  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

class CommentForm(ModelForm):
  class Meta:
    model = CommentModel
    fields = ('name' ,'event','description','image','video')

django-calendar/cal/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import logout,authenticate,login
from .models import *
from .utils import Calendar
from .forms import EventForm, CommentForm
from .weather import *


class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month
    
def event(request,pk):
    event_title = Event.objects.get(id=pk)
    post_likes = event_title.post_like.count()
    if request.user.is_authenticated:
        if request.method == "POST":
            if event_title.post_like.filter(id=request.user.id).exists():
                event_title.post_like.remove(request.user)
                event_title.save()
                return HttpResponseRedirect(reverse('cal:event',kwargs={'pk':pk})) 
            else:
                event_title.post_like.add(request.user)
                event_title.save()
                return HttpResponseRedirect(reverse('cal:event',kwargs={'pk':pk}))    
    else:
        return HttpResponseRedirect(reverse('cal:register_page'))
    context={
        'event_title': event_title,
        'id': pk,
        'post_likes':post_likes,  
    }
    return render(request, 'cal/selection.html',context) 

def new_event(request,event_id=None):
    if request.user.is_authenticated:
        instance = Event()
        if event_id:
            instance = get_object_or_404(Event, pk=event_id)
        form = EventForm(request.POST or None, instance=instance)
        if request.POST and form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('cal:calendar'))

        return render(request, 'cal/new_event.html', {'form': form}) 
    else:
        return HttpResponseRedirect(reverse('cal:register_page'))        

def delete(request,pk):
    Event.objects.get(id=pk).delete()
    return HttpResponseRedirect(reverse('cal:calendar'))

def delete_comment(request,pk):
    CommentModel.objects.get(id=pk).delete()
    return HttpResponseRedirect(reverse('cal:calendar'))

def edit(request,pk):
    instance = Event.objects.get(id=pk)
    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:event',kwargs={'pk':pk}))
    context={
        'form': form,
        'id': pk,
    }
    return render(request, 'cal/modify_event.html',context)

def delete_comment_selection(request,pk):
    comment_to_delete = CommentModel.objects.get(id=pk)
    context={
        'comment_to_delete':comment_to_delete,
    }
    return render(request,'cal/delete_comment.html',context)

def comment_selection(request,pk):
    comment_instance = CommentModel.objects.get(id=pk)
    context={
         'comment_instance':comment_instance
     }
    return render(request,'cal/comment_selection.html',context)

def edit_comment(request,pk):
    instance = CommentModel.objects.get(id=pk)
    commentform = CommentForm(request.POST or None, instance=instance)
    if request.POST and commentform.is_valid():
        commentform.save()
        return HttpResponseRedirect(reverse('cal:calendar'))
    context={
        'commentform': commentform,
    }    
    return render(request,'cal/edit_comment.html',context)

def image_upload_view(request,pk):
    comments = CommentModel.objects.all().filter(event=pk)
    event = Event.objects.get(id=pk)
    commentform = CommentForm(initial={'event':pk})
    if request.method == 'POST':
        commentform = CommentForm(request.POST, request.FILES)
        if commentform.is_valid():
            name = commentform.cleaned_data["name"]
            event = commentform.cleaned_data["event"]
            description = commentform.cleaned_data["description"]
            image = commentform.cleaned_data["image"]
            video = commentform.cleaned_data["video"]
            commentform = CommentModel(name=name,event=event,description=description,image=image,video=video)
            commentform.save()
            return HttpResponseRedirect(reverse('cal:upload',kwargs={'pk':pk}))
    context={
        'commentform':commentform,
        'comments':comments,
        'title':event.title,
    }
    return render(request, 'cal/upload.html',context)

def chat(request):
    return render(request, 'cal/chat.html')

def weather(request,pk):
    context={
        'day':day,
        'descreption':descreption,
        'temp':temp
    }
    return render(request,'cal/weather.html',context)

def login_page(request):
    form = AuthenticationForm()
    if request.method == "POST":
        form = AuthenticationForm(request=request,data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('cal:calendar'))
    return render(request,'cal/login.html',{'form':form})

def register_page(request):
    form = UserCreationForm()
    if request.method == "POST":
       form = UserCreationForm(request.POST)
       if form.is_valid():
           form.save()
           return HttpResponseRedirect(reverse('cal:login_page'))
    return render(request,'cal/register.html',{'form':form})

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('cal:calendar'))

django-calendar/chat/views.py
# chat/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'chat/index.html', {})

def room(request, room_name):
    return render(request, 'chat/room.html', {
        'room_name': room_name
    })

django-calendar/cal/templates/cal/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css"
    integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
  <title>Django Calendar App</title>
</head>

<body>

  <h1 class="title">{% block title %}{% endblock %}</h1>
  
  <div class="right">
  {% if user.is_authenticated %}
  <h7>Signed in as {{user.get_username}}<h7>
  <a class="btn btn-info " href="{% url 'cal:logout_view'%}"> Logout </a>
  {% else %}
  <a class="btn btn-info " href="{% url 'cal:login_page'%}"> Sign in </a>
  {%endif%}
  </div>
<br>
<br>
  <hr> <!--break line -->
  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>

  {% block script %}
  {% endblock %}
</body>
</html>

django-calendar/cal/templates/cal/calendar.html
{% extends 'cal/base.html' %}

{% block title %}
Calendar
{% endblock %}

{% block content %}
<br>
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info right" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
	<a class="btn btn-info right" href="{% url 'cal:new_event' %}"> New Event </a>
</div>
{{ calendar }}
{% endblock %}

django-calendar/cal/templates/cal/chat.html
{% extends 'cal/base.html' %}

{% block title %}
Chat
{% endblock %}

{% block content %}

<div class="right">
    <a class="btn btn-info left" class="right" href="{% url 'cal:calendar'%}"> Calendar </a>
</div>
<a class="btn btn-info" href="{{request.META.HTTP_REFERER}}"> Previous </a>
<div class="text-center">
    {% include 'chat/index.html' %}
{% endblock%}

django-calendar/cal/templates/cal/comment_selection.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="right"><a class="btn btn-info left" class="right" href="{% url 'cal:calendar'%}"> Calendar </a></div>
<a class="btn btn-info left,right" href="{{request.META.HTTP_REFERER}}"> Previous </a>
<div class="text-center">
<a class="btn btn-info " href="{% url 'cal:edit_comment' comment_instance.id%}"> Edit Comment</a> 
<a class="btn btn-info " href="{% url 'cal:delete_comment_selection' comment_instance.id%}"> Delete Comment</a>
</div>
{% endblock %}

django-calendar/cal/templates/cal/commentform.html
{% extends 'cal/base.html' %}

{% block title %}
Blog
{% endblock %}

{% block content %}
<div>
    <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
    <br></br><br></br>
<form method = "POST" action="">
    {% csrf_token %}
    {{commentform.as_p}}
    <input type="Submit" value="Submit"/>    
</form>
<br></br>
<div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
         {{ image_form.as_p }}
        <button type="submit">Upload</button>
      </form>
      
      {% if img_obj %}
        <h3>Succesfully uploaded : {{img_obj.title}}</h3>
        <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
      {% endif %} 
     </div>
</div>
<!-- {{i.name}} is the name that gets clicked on  -->
{% for i in comments %} {% if i.like %}  {{i.name}}, Event: <a style="color: blue;" href="{% url 'cal:comment_selection' i.id %}" > {{i.event}} </a>  {% else %} {{i.name}} Event: <a style="color:red;" href="{% url 'cal:comment_selection' i.id %}"> {{i.event}}, </a> {% endif %}<br>{{i.description}}</br><br> {% endfor %}
<div class="text-center"> 
<h2 class="btn btn-info"> Likes {{like}} </h2> 
<h2 class="btn btn-info"> Dislikes {{dislike}} </h2> 
</div>
{% endblock%}

django-calendar/cal/templates/cal/delete_comment.html
<a class="btn btn-info left" href="{% url 'cal:calendar'%}"> Calendar </a>
<br>
Are you sure you want to delete
<a class="btn btn-info right" href="{% url 'cal:delete_comment' comment_to_delete.id %}"> {{comment_to_delete.description}}?</a

django-calendar/cal/templates/cal/edit_comment.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="right"><a class="btn btn-info left" class="right" href="{% url 'cal:calendar'%}"> Calendar </a></div>
<a class="btn btn-info left,right" href="{{request.META.HTTP_REFERER}}"> Previous </a>
<div class="a">
<form method = "POST" action="">
    {% csrf_token %}
    {{commentform.as_p}}
    <input class="btn btn-info" type="Submit" value="Submit"/>    
</form>
</div>
{% endblock %}

django-calendar/cal/templates/cal/login.html
{% extends 'cal/base.html' %}

{% block title %}
Login
{% endblock %}

{% block content %}
<br></br>
<div class="a">
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input class="btn btn-info" type="submit" name="login user">
    </form>
    <p>Don't have an account
        <a href="{% url 'cal:register_page'%}">Sign up</a>
    </p>
    <a href="{% url 'cal:calendar'%}">Exit</a>
</div>
{% endblock %}

django-calendar/cal/templates/cal/modify_event.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="right">
  <a class="btn btn-info left" class="right" href="{% url 'cal:calendar'%}"> Calendar </a>
   </div>
  <a class="btn btn-info left,right"  href = "{{request.META.HTTP_REFERER}}"> Previous </a>
  <div class="text-center">
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>

{% endblock %}

django-calendar/cal/templates/cal/new_event.html
{% extends 'cal/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{form}}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
{% endblock %}

django-calendar/cal/templates/cal/register.html
{% extends 'cal/base.html' %}

{% block title %}
Register
{% endblock %}

{% block content %}
<br></br>

<div class="a">
    <form method="POST" action="">
        {% csrf_token %}
        {{form.errors}}
        {{form.username.label_tag}}
        {{form.username}}<br><br>
        {{form.password1.label_tag}}
        {{form.password1}}<br><br>
        {{form.password2.label_tag}}
        {{form.password2}} <br><br>
        <input class="btn btn-info" type="submit" name="create user">
    </form>
    <p>Already have an account
        <a href="{% url 'cal:login_page'%}">Login</a>
    </p>
        <a href="{% url 'cal:calendar'%}">Exit</a>
</div>

{% endblock%}

django-calendar/cal/templates/cal/selection.html
{% extends 'cal/base.html' %}

{% block title %}
{{event_title}}
{% endblock %}

{% block content %}

<div class="right">
<a class="btn btn-info left" class="right" href="{% url 'cal:calendar'%}"> Calendar </a>
 </div>
<a class="btn btn-info left,right" href="{% url 'cal:calendar'%}"> Previous </a>
<div class="text-center">
<a class="btn btn-info " href="{% url 'cal:upload' id%}"> Blog</a>
<a class="btn btn-info " href="{% url 'cal:chat'%}"> Chat</a>
<a class="btn btn-info " href="{% url 'cal:weather' id%}"> Weather </a>
<a class="btn btn-info " href="{% url 'cal:edit' id%}"> Edit Event </a>
<a class="btn btn-info " href="{% url 'cal:delete' id%}"> Delete Event </a>
<br>
<br>
<form method="POST">
{% csrf_token %}
<button class="btn btn-info" type="Submit" value="Like" href="{% url 'cal:event' id%}"> 
 {{post_likes}} Likes 
</form>
{% endblock %}

django-calendar/cal/templates/cal/upload.html
{% extends 'cal/base.html' %}

{% block title %}
{{title}}
{% endblock %}

{% block content %}
<div class="right">
  <a class="btn btn-info left" class="right" href="{% url 'cal:calendar'%}"> Calendar</a>
</div>
<a class="btn btn-info" href="{{request.META.HTTP_REFERER}}">Previous</a>
<br><br>
<div class="a">
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{commentform.errors}}
    {{commentform.name.label_tag}}
    {{commentform.name}}
    <br>
    <br>
    {{commentform.description.label_tag}}
    {{commentform.description}}
    <br>
    <br>
    Image:{{image.label_tag}}
    {{commentform.image}}
    <br>
    <br>
    Video:{{video.label_tag}}
    {{commentform.video}}
    <br>
    <br>
    {{event.label_tag}}
    {{commentform.event.as_hidden}}
    <input class="btn btn-info" type="Submit" value="Submit" />
  </form>
<hr>
</div>
<br>
<div class="text-center">
  {% for i in comments %}
    <a>{% if i.image %}<img src="{{i.image.url}}" , alt="" style="max-height:300px"> </a>
  {%endif%}
  {% if i.video %}
    <video width='530' controls>
      <source src="{{i.video.url}}" type='video/mp4'>
    </video>
  {%endif%}
  <div class="text-center"> {{i.name}}, <br> <a href="{% url 'cal:comment_selection' i.id %}">
    {{i.description}} </a> </br>Posted on {{i.created}}</br><br>
    <hr>
  </div>
  
  {% endfor %}
  {% endblock%}

django-calendar/cal/templates/cal/weather.html
{% extends 'cal/base.html' %}

{% block title %}
Weather
{% endblock %}

{% block content %}
<div class="right"><a class="btn btn-info left" class="right" href="{% url 'cal:calendar'%}"> Calendar </a></div>
<a class="btn btn-info left,right" href="{{request.META.HTTP_REFERER}}"> Previous </a>
<br><br><br><br>
<table id="weather">
    <tr><th>Day:</th>{%for i in day %}<td> {{i}}</td> {%endfor%}</tr>
    <tr><th>Description</th> {%for j in descreption %}<td>{{j}}</td>{%endfor%}</tr>
    <tr><th>Temp</th>{%for k in temp %}<td>{{k}}</td> {%endfor%}</tr>
</table>
{% endblock%}